from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib as mpl
import matplotlib.pyplot as plt

FAMILY_ORDER = ("openai", "anthropic", "google", "deepseek", "qwen", "meta")
FAMILY_LABELS = {
    "openai": "OpenAI",
    "anthropic": "Anthropic",
    "google": "Google",
    "deepseek": "DeepSeek",
    "qwen": "Qwen",
    "meta": "Llama",
}
FAMILY_COLORS = {
    "openai": "#D97706",
    "anthropic": "#DB2777",
    "google": "#059669",
    "deepseek": "#2563EB",
    "qwen": "#7C3AED",
    "meta": "#CA8A04",
}


def _load(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("pilot summary must be one JSON object")
    if payload.get("schema_version") != "faireval-hosted-pilot-operational-summary-v1":
        raise ValueError("unsupported pilot summary schema")
    if payload.get("scientific_outcomes_inspected") is not False:
        raise ValueError("pilot reporting source must be outcome-blind")
    return payload


def render_table(payload: dict[str, Any]) -> str:
    families = payload["families"]
    rows: list[str] = []
    for family in FAMILY_ORDER:
        row = families[family]
        rows.append(
            "{} & {} & {} & {} & {} & {:.4f} \\\\".format(
                FAMILY_LABELS[family],
                int(row["cells"]),
                int(row["users_touched"]),
                int(row["identity_complete_users"]),
                int(row["personality_complete_users"]),
                float(row["observed_request_window_cost_rmb"]),
            )
        )
    return "\n".join(
        [
            "% AUTO-GENERATED by scripts/render_hosted_pilot_operational.py; DO NOT EDIT.",
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Hosted black-box FairSynth operational pilot (99/1,080 cells). Pair columns count structurally complete users, not fairness or utility outcomes; RMB is observed request-window gateway balance movement.}",
            "\\label{tab:hosted-pilot-operational}",
            "\\scriptsize",
            "\\setlength{\\tabcolsep}{3.0pt}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Family & Cells & Users touched & Identity-complete & Personality-complete & Request-window RMB \\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )


def render_figure(payload: dict[str, Any], output: Path) -> None:
    """Render a compact black-box operational pilot summary.

    The figure intentionally contains no capability, fairness, utility, or
    personality-effect estimates because the 99-cell pilot was outcome-blind
    and underpowered for the preregistered hosted inference.
    """
    families = payload["families"]
    labels = [FAMILY_LABELS[f] for f in FAMILY_ORDER]
    colors = [FAMILY_COLORS[f] for f in FAMILY_ORDER]
    cells = [int(families[f]["cells"]) for f in FAMILY_ORDER]
    identity = [int(families[f]["identity_complete_users"]) for f in FAMILY_ORDER]
    personality = [int(families[f]["personality_complete_users"]) for f in FAMILY_ORDER]
    costs = [float(families[f]["observed_request_window_cost_rmb"]) for f in FAMILY_ORDER]

    mpl.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 8.0,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "axes.edgecolor": "#64748B",
        "axes.labelcolor": "#172033",
        "xtick.color": "#475569",
        "ytick.color": "#475569",
        "text.color": "#172033",
    })

    fig, (ax_cov, ax_cost) = plt.subplots(
        1, 2, figsize=(6.75, 2.85), gridspec_kw={"width_ratios": [1.05, 1.15]}
    )
    y = list(range(len(labels)))

    # Panel A: execution and paired-user structure.
    bars = ax_cov.barh(y, cells, color=colors, alpha=0.86, height=0.58)
    ax_cov.set_yticks(y, labels)
    ax_cov.invert_yaxis()
    ax_cov.set_xlim(0, 20.5)
    ax_cov.set_xlabel("Completed cells")
    ax_cov.set_title("(a) Coverage", loc="left", fontsize=8.5, fontweight="bold")
    ax_cov.grid(axis="x", linewidth=0.45, alpha=0.28)
    ax_cov.spines[["top", "right"]].set_visible(False)
    for bar, n in zip(bars, cells, strict=True):
        ax_cov.text(
            bar.get_width() + 0.35,
            bar.get_y() + bar.get_height() / 2,
            f"{n}",
            va="center",
            fontsize=7.0,
        )

    # Panel B: observed request-window spend.
    bars2 = ax_cost.barh(y, costs, color=colors, alpha=0.86, height=0.58)
    ax_cost.set_yticks(y, [""] * len(labels))
    ax_cost.invert_yaxis()
    ax_cost.set_xlabel("Request-window RMB")
    ax_cost.set_title("(b) Gateway balance movement", loc="left", fontsize=8.5, fontweight="bold")
    ax_cost.grid(axis="x", linewidth=0.45, alpha=0.28)
    ax_cost.spines[["top", "right"]].set_visible(False)
    max_cost = max(costs) if costs else 1.0
    ax_cost.set_xlim(0, max_cost * 1.22)
    for bar, cost in zip(bars2, costs, strict=True):
        ax_cost.text(
            bar.get_width() + max_cost * 0.018,
            bar.get_y() + bar.get_height() / 2,
            f"{cost:.2f}",
            va="center",
            fontsize=7.0,
        )

    pair_note = (
        f"Each family: ID-complete={min(identity)}; personality-complete={min(personality)} users. "
        "Outcome-blind pilot: 99/1,080 cells; no hosted fairness/personality inference."
    )
    fig.text(
        0.5,
        0.005,
        pair_note,
        ha="center",
        va="bottom",
        fontsize=6.7,
        color="#64748B",
    )
    fig.tight_layout(rect=(0.0, 0.055, 1.0, 1.0), w_pad=1.0)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary",
        default="provenance/hosted_fairsynth_pilot99_operational_summary.json",
    )
    parser.add_argument(
        "--table",
        default="paper/generated/hosted_pilot_operational_table.tex",
    )
    parser.add_argument(
        "--figure",
        default="paper/figures/hosted_pilot_blackbox_summary.pdf",
    )
    args = parser.parse_args()

    payload = _load(Path(args.summary))
    table_path = Path(args.table)
    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(render_table(payload), encoding="utf-8", newline="\n")
    render_figure(payload, Path(args.figure))
    print(json.dumps({
        "schema_version": "faireval-hosted-pilot-paper-artifacts-v1",
        "table": str(table_path),
        "figure": args.figure,
        "scientific_outcomes_inspected": False,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
