from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


MODEL_LABELS = {
    "qwen25_local": "Qwen2.5-7B local",
    "phi35_local": "Phi-3.5-mini local",
}


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            if not isinstance(row, dict):
                raise ValueError(f"{path}:{line_no}: expected JSON object")
            rows.append(row)
    if not rows:
        raise ValueError(f"{path} contains no white-box summaries")
    return rows


def _fmt(value: Any, digits: int = 3) -> str:
    if value is None:
        return "--"
    return f"{float(value):.{digits}f}"


def _rho(row: dict[str, Any], field: str) -> str:
    value = row.get(field)
    if not isinstance(value, dict):
        return "--"
    return _fmt(value.get("rho"))


def _escape(value: Any) -> str:
    return str(value).replace("_", "\\_")


def render(rows: list[dict[str, Any]]) -> str:
    body: list[str] = []
    for row in sorted(rows, key=lambda x: (str(x.get("dataset")), str(x.get("model_family")))):
        family = str(row.get("model_family"))
        body.append(
            "{} & {} & {} & {} & {} \\\\".format(
                MODEL_LABELS.get(family, _escape(family)),
                _fmt(100.0 * float(row.get("invalid_rate", 0.0)), 1),
                _fmt(row.get("mean_generated_token_logprob_valid_mean")),
                _fmt(row.get("mean_top1_top2_logit_margin_valid_mean")),
                _rho(row, "mean_generated_token_logprob_spearman_ndcg"),
            )
        )

    return "\n".join(
        [
            "% AUTO-GENERATED by scripts/render_whitebox_paper.py; DO NOT EDIT BY HAND.",
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Exploratory local generation-score diagnostics ($N=1{,}440$ cells/model). Scores are uncalibrated; $\\rho$ is descriptive Spearman association with nDCG@10.}",
            "\\label{tab:whitebox-generated}",
            "\\scriptsize",
            "\\setlength{\\tabcolsep}{3pt}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            "Model & Invalid (\\%) & Mean log-$p$ & Top1--top2 margin & $\\rho$(log-$p$, nDCG) \\\\",
            "\\midrule",
            *body,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\vspace{0.4mm}",
            "\\parbox{0.985\\linewidth}{\\scriptsize These scores are auxiliary local diagnostics and are neither calibrated confidence estimates nor pooled with hosted-model evidence.}",
            "\\end{table}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render audited local white-box summaries into the ECIR paper"
    )
    parser.add_argument("--summary-jsonl", required=True)
    parser.add_argument(
        "--output",
        default="paper/generated/whitebox_summary_table.tex",
    )
    args = parser.parse_args()

    rows = _read_jsonl(Path(args.summary_jsonl))
    text = render(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
