from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt

FAMILY_ORDER = ("openai", "anthropic", "google", "deepseek", "qwen", "meta")
FAMILY_LABELS = {
    "openai": "OpenAI",
    "anthropic": "Anthropic",
    "google": "Google",
    "deepseek": "DeepSeek",
    "qwen": "Qwen",
    "meta": "Llama",
}


def _load(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("pilot summary must be one JSON object")
    if payload.get("schema_version") != "faireval-hosted-pilot-operational-summary-v1":
        raise ValueError("unsupported pilot summary schema")
    if payload.get("scientific_outcomes_inspected") is not False:
        raise ValueError("pilot reporting source must be outcome-blind")
    return payload


def render_table(payload: dict[str, Any]) -> str:
    families = payload["families"]
    rows: list[str] = []
    for family in FAMILY_ORDER:
        row = families[family]
        rows.append(
            "{} & {} & {} & {} & {} & {:.4f} \\\\".format(
                FAMILY_LABELS[family],
                int(row["cells"]),
                int(row["users_touched"]),
                int(row["identity_complete_users"]),
                int(row["personality_complete_users"]),
                float(row["observed_request_window_cost_rmb"]),
            )
        )
    return "\n".join(
        [
            "% AUTO-GENERATED by scripts/render_hosted_pilot_operational.py; DO NOT EDIT.",
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Outcome-blind hosted FairSynth operational pilot. The client budget guard stopped the campaign after 99/1,080 planned cells. Identity/personality columns report structurally complete paired users, not fairness or utility outcomes. Request-window cost is gateway balance movement attributable between each cell's before/after checks and therefore need not sum exactly to the ledger-wide spend.}",
            "\\label{tab:hosted-pilot-operational}",
            "\\scriptsize",
            "\\setlength{\\tabcolsep}{3.0pt}",
            "\\resizebox{\\textwidth}{!}{%",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Family & Cells & Users touched & Identity-complete & Personality-complete & Request-window RMB \\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )


def render_figure(payload: dict[str, Any], output: Path) -> None:
    families = payload["families"]
    labels = [FAMILY_LABELS[f] for f in FAMILY_ORDER]
    costs = [float(families[f]["observed_request_window_cost_rmb"]) for f in FAMILY_ORDER]
    cells = [int(families[f]["cells"]) for f in FAMILY_ORDER]

    fig, ax = plt.subplots(figsize=(6.7, 3.8))
    bars = ax.barh(labels, costs)
    ax.invert_yaxis()
    ax.set_xlabel("Observed request-window balance movement (RMB)")
    ax.set_title("Hosted FairSynth pilot: operational cost profile", loc="left", fontweight="bold")
    ax.grid(axis="x", linewidth=0.5, alpha=0.45)
    max_cost = max(costs) if costs else 1.0
    for bar, cost, n in zip(bars, costs, cells, strict=True):
        ax.text(
            bar.get_width() + max_cost * 0.015,
            bar.get_y() + bar.get_height() / 2,
            f"{cost:.2f} RMB / {n} cells",
            va="center",
            fontsize=7.5,
        )
    ax.text(
        0.99,
        0.02,
        "Operational pilot only; no recommendation outcomes shown",
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=7.2,
    )
    fig.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight", pad_inches=0.04)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary",
        default="provenance/hosted_fairsynth_pilot99_operational_summary.json",
    )
    parser.add_argument(
        "--table",
        default="paper/generated/hosted_pilot_operational_table.tex",
    )
    parser.add_argument(
        "--figure",
        default="paper/figures/hosted_pilot_cost_profile.pdf",
    )
    args = parser.parse_args()

    payload = _load(Path(args.summary))
    table_path = Path(args.table)
    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(render_table(payload), encoding="utf-8", newline="\n")
    render_figure(payload, Path(args.figure))
    print(json.dumps({
        "schema_version": "faireval-hosted-pilot-paper-artifacts-v1",
        "table": str(table_path),
        "figure": args.figure,
        "scientific_outcomes_inspected": False,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
