from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib as mpl
import matplotlib.pyplot as plt

FAMILY_ORDER = ("openai", "anthropic", "google", "deepseek", "qwen", "meta")
FAMILY_LABELS = {
    "openai": "OpenAI",
    "anthropic": "Anthropic",
    "google": "Google",
    "deepseek": "DeepSeek",
    "qwen": "Qwen",
    "meta": "Llama",
}
FAMILY_COLORS = {
    "openai": "#D97706",
    "anthropic": "#DB2777",
    "google": "#059669",
    "deepseek": "#2563EB",
    "qwen": "#7C3AED",
    "meta": "#CA8A04",
}


def _load(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("pilot summary must be one JSON object")
    if payload.get("schema_version") != "faireval-hosted-pilot-operational-summary-v1":
        raise ValueError("unsupported pilot summary schema")
    if payload.get("scientific_outcomes_inspected") is not False:
        raise ValueError("pilot reporting source must be outcome-blind")
    return payload


def render_table(payload: dict[str, Any]) -> str:
    families = payload["families"]
    rows: list[str] = []
    for family in FAMILY_ORDER:
        row = families[family]
        rows.append(
            "{} & {} & {} & {} & {} & {:.4f} \\\\".format(
                FAMILY_LABELS[family],
                int(row["cells"]),
                int(row["users_touched"]),
                int(row["identity_complete_users"]),
                int(row["personality_complete_users"]),
                float(row["observed_request_window_cost_rmb"]),
            )
        )
    return "\n".join(
        [
            "% AUTO-GENERATED by scripts/render_hosted_pilot_operational.py; DO NOT EDIT.",
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Hosted black-box FairSynth operational pilot (99/1,080 cells). Pair columns count structurally complete users, not fairness or utility outcomes; RMB is observed request-window gateway balance movement.}",
            "\\label{tab:hosted-pilot-operational}",
            "\\scriptsize",
            "\\setlength{\\tabcolsep}{3.0pt}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Family & Cells & Users touched & Identity-complete & Personality-complete & Request-window RMB \\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )


def render_figure(payload: dict[str, Any], output: Path) -> None:
    """Render six small-multiple radar charts for *operational coverage* only.

    This deliberately mirrors the visual language of a model-profile figure while
    avoiding unsupported capability/performance claims. Every axis is normalized
    to the frozen per-family campaign plan: 180 cells and 30 users.
    """
    import math

    families = payload["families"]
    model_ids = {
        "openai": "gpt-5.6-terra",
        "anthropic": "claude-sonnet-5",
        "google": "gemini-3.8-flash",
        "deepseek": "deepseek-v4.1-flash",
        "qwen": "qwen3.8-max",
        "meta": "llama-4-maverick",
    }
    axes_labels = ("cells", "users", "ID pairs", "P pairs", "all-6")
    angles = [2.0 * math.pi * i / len(axes_labels) for i in range(len(axes_labels))]
    closed_angles = angles + angles[:1]

    mpl.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 7.5,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "text.color": "#172033",
        "axes.edgecolor": "#94A3B8",
    })

    fig, axes = plt.subplots(
        2, 3,
        figsize=(6.75, 4.55),
        subplot_kw={"projection": "polar"},
    )
    for ax, family in zip(axes.ravel(), FAMILY_ORDER, strict=True):
        row = families[family]
        values = [
            float(row["cells"]) / 180.0,
            float(row["users_touched"]) / 30.0,
            float(row["identity_complete_users"]) / 30.0,
            float(row["personality_complete_users"]) / 30.0,
            float(row["all_six_conditions_complete_users"]) / 30.0,
        ]
        closed = values + values[:1]
        color = FAMILY_COLORS[family]

        ax.set_theta_offset(math.pi / 2.0)
        ax.set_theta_direction(-1)
        ax.plot(closed_angles, closed, linewidth=1.35, color=color)
        ax.fill(closed_angles, closed, alpha=0.22, color=color)
        ax.scatter(angles, values, s=10, color=color, zorder=3)

        ax.set_xticks(angles)
        ax.set_xticklabels(axes_labels, fontsize=6.4)
        ax.set_ylim(0.0, 0.125)
        ax.set_yticks([0.05, 0.10])
        ax.set_yticklabels(["5%", "10%"], fontsize=5.8, color="#64748B")
        ax.set_rlabel_position(20)
        ax.grid(linewidth=0.45, alpha=0.35)
        ax.spines["polar"].set_color("#CBD5E1")
        ax.plot(
            [0.0, 2.0 * math.pi],
            [0.10, 0.10],
            linestyle="--",
            linewidth=0.8,
            color="#475569",
            alpha=0.75,
        )
        ax.set_title(
            f"{FAMILY_LABELS[family]}\n({model_ids[family]})",
            fontsize=7.3,
            fontweight="bold",
            pad=9,
        )

    fig.text(
        0.5,
        0.012,
        "Operational coverage relative to the frozen full plan (180 cells / 30 users per family). "
        "Dashed ring = 10% coverage. These are not capability, utility, or fairness scores.",
        ha="center",
        va="bottom",
        fontsize=6.4,
        color="#64748B",
    )
    fig.tight_layout(rect=(0.01, 0.055, 0.99, 0.995), h_pad=0.55, w_pad=0.35)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary",
        default="provenance/hosted_fairsynth_pilot99_operational_summary.json",
    )
    parser.add_argument(
        "--table",
        default="paper/generated/hosted_pilot_operational_table.tex",
    )
    parser.add_argument(
        "--figure",
        default="paper/figures/hosted_pilot_blackbox_summary.pdf",
    )
    args = parser.parse_args()

    payload = _load(Path(args.summary))
    table_path = Path(args.table)
    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(render_table(payload), encoding="utf-8", newline="\n")
    render_figure(payload, Path(args.figure))
    print(json.dumps({
        "schema_version": "faireval-hosted-pilot-paper-artifacts-v1",
        "table": str(table_path),
        "figure": args.figure,
        "scientific_outcomes_inspected": False,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
